function Spinner = importData(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  SPINNER = IMPORTDATA(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  SPINNER = IMPORTDATA(FILE, SHEET) reads from the specified worksheet.
%
%  SPINNER = IMPORTDATA(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Spinner = importdata("/Users/nathansmac/Desktop/Wheel/DataDownload/Spinner_1.xlsx", "2021-02-16_010351", [2, 3509]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Feb-2021 21:34:31

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    error('please input a sheet name');
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    error('please input the data lines');
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Time", "Left_value", "Centre_value", "Right_value"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Import the data
Spinner = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Spinner = [Spinner; tb]; %#ok<AGROW>
end

end