function Directory = importDirectory_weights(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  DIRECTORY = IMPORTDIRECTORY_WEIGHTS(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  DIRECTORY = IMPORTDIRECTORY_WEIGHTS(FILE, SHEET) reads from the specified
%  worksheet.
%
%  DIRECTORY = IMPORTDIRECTORY_WEIGHTS(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  Directory = importDirectory_weights("/Users/nathansmac/Dropbox/RunningWheel/ABA_1.xlsx", "Directory", [2, 17]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-Mar-2021 21:57:20

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 24];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":D" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["TabNumber", "TabName", "Date", "Experimental_Day"];
opts.VariableTypes = ["double", "string", "datetime", "string"];

% Specify variable properties
opts = setvaropts(opts, ["TabName", "Experimental_Day"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["TabName", "Experimental_Day"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Date", "InputFormat", "");

% Import the data
Directory = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":D" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Directory = [Directory; tb]; %#ok<AGROW>
end

end