function ABA = importWeights(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  ABA = IMPORTWEIGHTS(FILE) reads data from the first worksheet in the
%  Microsoft Excel spreadsheet file named FILE.  Returns the data as a
%  table.
%
%  ABA = IMPORTWEIGHTS(FILE, SHEET) reads from the specified worksheet.
%
%  ABA = IMPORTWEIGHTS(FILE, SHEET, DATALINES) reads from the specified
%  worksheet for the specified row interval(s). Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  ABA = importWeights("/Users/nathansmac/Dropbox/RunningWheel/ABA_1.xlsx", "24Feb2021", [6, 13]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Mar-2021 21:52:24

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [6, 21];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":G" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Mouse", "MouseWeightg930AM", "OldFoodWeightg930AM", "NewFoodWeightg930AM", "PostFoodWeightg330PM", "WaterWeightg930AM", "Notes"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, "Notes", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Notes", "EmptyFieldRule", "auto");

% Import the data
ABA = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":G" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    ABA = [ABA; tb]; %#ok<AGROW>
end

end